### ISSUE TITLE
Can you hand out your paper?

### ISSUE THREAD

**Issue by G22-web** [djz233/D-DGCN#1]
I can't find it online, thank you！ gaoxue@hnu.edu.cn

**Comment by freeyangHaha** [comment]
> I can't find it online, thank you！ [gaoxue@hnu.edu.cn](mailto:gaoxue@hnu.edu.cn)
The paper is "Orders Are Unwanted: Dynamic Deep Graph Convolutional Network for Personality Detection".

**Comment by TaoYang225** [comment]
Hi, the paper is available at https://arxiv.org/abs/2212.01515
