### ISSUE TITLE
有关加载后训练好的BERT模型参数不匹配问题

### ISSUE THREAD

**Issue by Wen-05-coder** [djz233/D-DGCN#6]
请问为什么在加载bert-pretrained.pth模型时会报错参数不匹配呢？
RuntimeError: Error(s) in loading state_dict for UPF_dgcn:
	size mismatch for pretrain_models.embeddings.word_embeddings.weight: copying a param with shape torch.Size([28996, 768]) from checkpoint, the shape in current model is torch.Size([30522, 768]).

**Comment by djz233** [comment]
we use bert-base-**cased**, but not uncased version

**Comment by Wen-05-coder** [comment]
Thank you for your timely answer, the problem has been solved!!发自我的 iPhone在 2023年12月7日，16:47，djz233 ***@***.***> 写道：﻿
we use bert-base-cased, but not uncased version
